/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caso2;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import javafx.scene.shape.Circle;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author kduran
 */
public class Frame extends javax.swing.JFrame implements ActionListener{
    Timer tm=new Timer(1200, this);
    private int cantidad;
    private Color color;
    private int direccion;
    private int velocidad;
    private int patron;
    ViewPanel view;
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        view = new ViewPanel(this);
//        Shape circle = new Ellipse2D.Double(100, 100, 10, 10);
//        CustomShape custom = new CustomShape(circle, color, "uno");
//        view.addShape(custom);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        System.out.println("w " + jPanel1.getWidth() + " h " + jPanel1.getHeight() +
//                " x " +jPanel1.getX() + " y " + jPanel1.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        direccionCB = new javax.swing.JComboBox<>();
        velocidadCB = new javax.swing.JComboBox<>();
        patronCB = new javax.swing.JComboBox<>();
        coloCB = new javax.swing.JComboBox<>();
        cantidadTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        direccionCB.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        direccionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direccion 0º", "Direccion 45º", "Direccion 90º", "Direccion 135º", "Direccion 180º", "Direccion 225º", "Direccion 270º", "Direccion 315º" }));
        direccionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionCBActionPerformed(evt);
            }
        });

        velocidadCB.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        velocidadCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Velocidad 1", "Velocidad 2", "Velocidad 3", "Velocidad 4", "Velocidad 5", "Velocidad 6", "Velocidad 7", "Velocidad 8", "Velocidad 9", "Velocidad 10" }));

        patronCB.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        patronCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prototype", "Factory Method", "Builder", "Object Pool" }));

        coloCB.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        coloCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Verde", "Amarillo", "Negro", "Azul", "Rosado", "Morado", "Blanco" }));

        cantidadTF.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        cantidadTF.setText("Cantidad");

        jButton1.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        jButton2.setText("Finalizar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(coloCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(direccionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(velocidadCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patronCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cantidadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(coloCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(direccionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(velocidadCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(patronCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(88, 88, 88))
        );

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 48)); // NOI18N
        jLabel1.setText("Bolas Locas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 528, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void direccionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cantidad = Integer.parseInt(cantidadTF.getText());
        color = getColorNumber(coloCB.getSelectedItem().toString());
        velocidad = getVelocidad(velocidadCB.getSelectedItem().toString());
        direccion = getDireccion(direccionCB.getSelectedItem().toString());
        patron = getPatron(patronCB.getSelectedItem().toString());
        System.out.println("" + patron);
        creator.creaBolas(patron, cantidad, velocidad, color, direccion, view);
//        System.out.println();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private Creador creator = new Creador();
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    
// TODO, insertar un grafic en un panel desde aca para poner los puntos, o intentar crearlo y lueo ponerlo en el de aca
    // metodo que verifique 

//    public void paint(Graphics g) {
// 
//  Graphics2D g2d = (Graphics2D)g;
// 
//  int x = 100;
// 
//  int y = 100;
//
////  g2d.drawOval(x, y, 10, 10); 
////  g2d.drawOval(120, y, 10, 10); 
////        for (int i = 0; i < 10; i++) {
////            g2d.drawOval(120+(i*10), y, 10, 10);
////        }
//        jPanel1.paintComponents(g2d);
//}
    
    
    private Color getColorNumber(String name){
        switch(name) {
            case "Rojo":
              return new Color(255, 0, 0);
            case "Verde":
              return new Color(51,204,0);
            case "Amarillo":
              return new Color(255,255,102);
            case "Negro":
              return new Color(0,0,0);
            case "Azul":
              return new Color(51,51,255);
            case "Rosado":
              return new Color(255,102,255);
            case "Morado":
              return new Color(102,0,102);
            case "Blanco":
              return new Color(255,255,255);
            default:
                return new Color(255,255,255);
          }
    }
    
    private int getVelocidad(String velocidad){
        switch(velocidad) {
            case "Velocidad 1":
              return 10000;
            case "Velocidad 2":
              return 10000;
            case "Velocidad 3":
              return 10000;
            case "Velocidad 4":
              return 10000;
            case "Velocidad 5":
              return 10000;
            case "Velocidad 6":
              return 10000;
            case "Velocidad 7":
              return 10000;
            case "Velocidad 8":
              return 10000;
            case "Velocidad 9":
              return 10000;
             case "Velocidad 10":
              return 10000;
            default:
                return 0;
          }
    } 
    
    private int getDireccion(String direccion){
        switch(direccion) {
            case "Direccion 0º":
              return 0;
            case "Direccion 45º":
              return 45;
            case "Direccion 90º":
              return 90;
            case "Direccion 135º":
              return 135;
            case "Direccion 180º":
              return 180;
            case "Direccion 225º":
              return 225;
            case "Direccion 270º":
              return 270;
            case "Direccion 315º":
              return 315;
            default:
                return 0;
          }
    } 
     public int getPatron(String patron) {
         switch(patron) {
            case "Prototype":
              return 1;
            case "Factory Method":
              return 2;
            case "Builder":
              return 3;
            case "Object Pool":
              return 4;
            default:
                return 0;
          }
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadTF;
    private javax.swing.JComboBox<String> coloCB;
    private javax.swing.JComboBox<String> direccionCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> patronCB;
    private javax.swing.JComboBox<String> velocidadCB;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
