/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caso1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author raque
 */
public class mainUsuario extends javax.swing.JFrame implements ActionListener{

    
     private Combo pedido;
     private PlatoFuerte platofuerte;
     private ArrayList<Object> pedidos;
     private ArrayList<Producto> productos;
     private int numCombo = 0;
     private int numPlatoFuerte = 0;
     private int numProducto = 0;
     Factory fac = new Factory();
    
     
   
//no me sirve que reciba una lista de productos porque debo recorrerla innecesariamente
    /**
     * Creates new form mainUsuario
     */
    public mainUsuario() {
        initComponents();
        //pedido = new Combo();
        
        pedidos = new ArrayList<>();
        productos = new ArrayList<>();
 
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo2 = new javax.swing.JButton();
        combo3 = new javax.swing.JButton();
        combo4 = new javax.swing.JButton();
        combo5 = new javax.swing.JButton();
        combo6 = new javax.swing.JButton();
        combo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uvas = new javax.swing.JButton();
        patatas = new javax.swing.JButton();
        maiz = new javax.swing.JButton();
        tresleches = new javax.swing.JButton();
        pure = new javax.swing.JButton();
        papas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ensalada = new javax.swing.JButton();
        cafe = new javax.swing.JButton();
        te = new javax.swing.JButton();
        natural = new javax.swing.JButton();
        frozen = new javax.swing.JButton();
        gaseosa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pagar = new javax.swing.JButton();
        batido = new javax.swing.JButton();
        pedir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pollo = new javax.swing.JButton();
        sandwich = new javax.swing.JButton();
        wrap = new javax.swing.JButton();
        pizza = new javax.swing.JButton();
        hamburguesa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hotdog = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo2.setText("2");
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, 80));

        combo3.setText("3");
        combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3ActionPerformed(evt);
            }
        });
        getContentPane().add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, 80));

        combo4.setText("4");
        combo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4ActionPerformed(evt);
            }
        });
        getContentPane().add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 100, 80));

        combo5.setText("5");
        combo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo5ActionPerformed(evt);
            }
        });
        getContentPane().add(combo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 100, 80));

        combo6.setText("6");
        combo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo6ActionPerformed(evt);
            }
        });
        getContentPane().add(combo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 100, 80));

        combo1.setText("1");
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, 80));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel1.setText("COMBOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 290, -1));

        uvas.setText("UVAS");
        uvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvasActionPerformed(evt);
            }
        });
        getContentPane().add(uvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 80));

        patatas.setText("PATATAS");
        patatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patatasActionPerformed(evt);
            }
        });
        getContentPane().add(patatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 100, 80));

        maiz.setText("MAÍZ");
        maiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maizActionPerformed(evt);
            }
        });
        getContentPane().add(maiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 100, 80));

        tresleches.setText("3 LECHES");
        tresleches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treslechesActionPerformed(evt);
            }
        });
        getContentPane().add(tresleches, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 100, 80));

        pure.setText("PURÉ");
        pure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pureActionPerformed(evt);
            }
        });
        getContentPane().add(pure, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 100, 80));

        papas.setText("PAPAS");
        papas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papasActionPerformed(evt);
            }
        });
        getContentPane().add(papas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 80));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel2.setText("ADICIONALES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 270, 30));

        ensalada.setText("ENSALADA");
        ensalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensaladaActionPerformed(evt);
            }
        });
        getContentPane().add(ensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 100, 80));

        cafe.setText("CAFÉ");
        cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeActionPerformed(evt);
            }
        });
        getContentPane().add(cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, 80));

        te.setText("TÉ");
        te.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teActionPerformed(evt);
            }
        });
        getContentPane().add(te, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 100, 80));

        natural.setText("NATURAL");
        natural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naturalActionPerformed(evt);
            }
        });
        getContentPane().add(natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 100, 80));

        frozen.setText("FROZEN");
        frozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frozenActionPerformed(evt);
            }
        });
        getContentPane().add(frozen, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, 80));

        gaseosa.setText("GASEOSA");
        gaseosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaseosaActionPerformed(evt);
            }
        });
        getContentPane().add(gaseosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 80));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel3.setText("BEBIDAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 293, 82));

        pagar.setText("PAGAR");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        getContentPane().add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 110, 40));

        batido.setText("BATIDO");
        batido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batidoActionPerformed(evt);
            }
        });
        getContentPane().add(batido, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 100, 80));

        pedir.setText("PEDIR");
        pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirActionPerformed(evt);
            }
        });
        getContentPane().add(pedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 110, 40));

        jLabel4.setText("pollo, refresco, papas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel5.setText("hot dog, puré, gaseosa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel6.setText("Hamburguesa, papas, refresco");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel7.setText("wrap, papas, 3 leches, gaseosa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel8.setText("pizza, gaseosa");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel9.setText("sandwich, papas, 3 leches, gaseosa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 48)); // NOI18N
        jLabel10.setText("COMBOSTAR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 293, 82));

        pollo.setText("POLLO");
        pollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polloActionPerformed(evt);
            }
        });
        getContentPane().add(pollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 100, 80));

        sandwich.setText("SANDWICH");
        sandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwichActionPerformed(evt);
            }
        });
        getContentPane().add(sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 100, 80));

        wrap.setText("WRAP");
        wrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrapActionPerformed(evt);
            }
        });
        getContentPane().add(wrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 100, 80));

        pizza.setText("PIZZA");
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });
        getContentPane().add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 100, 80));

        hamburguesa.setText("HAMBURGUESA");
        hamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguesaActionPerformed(evt);
            }
        });
        getContentPane().add(hamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 120, 80));

        jLabel11.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel11.setText("PLATOS FUERTES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 293, 82));

        hotdog.setText("HOT DOG");
        hotdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotdogActionPerformed(evt);
            }
        });
        getContentPane().add(hotdog, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 100, 80));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, 370, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
         this.pagar.addActionListener(this);  
    }//GEN-LAST:event_pagarActionPerformed

    private void pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirActionPerformed
        // TODO add your handling code here:
         this.pedir.addActionListener(this);
    }//GEN-LAST:event_pedirActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
       
 
        numCombo = 1;
        this.combo1.addActionListener(this);
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        // TODO add your handling code here:
       
        numCombo = 2;
        this.combo2.addActionListener(this);
        
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3ActionPerformed
        // TODO add your handling code here:
        
        numCombo = 3;
        this.combo3.addActionListener(this);
        
    }//GEN-LAST:event_combo3ActionPerformed

    private void combo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4ActionPerformed
        // TODO add your handling code here:
      
        numCombo = 4;
        this.combo4.addActionListener(this);
      
    }//GEN-LAST:event_combo4ActionPerformed

    private void combo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo5ActionPerformed
        // TODO add your handling code here:
        
        numCombo = 5;
        this.combo5.addActionListener(this);
      
        
    }//GEN-LAST:event_combo5ActionPerformed

    private void combo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo6ActionPerformed
        // TODO add your handling code here:
        
        numCombo = 6;
        this.combo6.addActionListener(this);
       
    }//GEN-LAST:event_combo6ActionPerformed

    private void papasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papasActionPerformed
        // TODO add your handling code here:
        numProducto = 1;
        this.papas.addActionListener(this);
    }//GEN-LAST:event_papasActionPerformed

    private void uvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvasActionPerformed
        // TODO add your handling code here:
        numProducto = 4;
        this.uvas.addActionListener(this);
    }//GEN-LAST:event_uvasActionPerformed

    private void patatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patatasActionPerformed
        // TODO add your handling code here:
        numProducto = 6;
         this.patatas.addActionListener(this);
    }//GEN-LAST:event_patatasActionPerformed

    private void maizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maizActionPerformed
        // TODO add your handling code here:
        numProducto = 5;
        this.maiz.addActionListener(this);
    }//GEN-LAST:event_maizActionPerformed

    private void treslechesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treslechesActionPerformed
        // TODO add your handling code here:
        numProducto = 3;
        this.tresleches.addActionListener(this);
    }//GEN-LAST:event_treslechesActionPerformed

    private void ensaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensaladaActionPerformed
        // TODO add your handling code here:
        numProducto = 7;
        this.ensalada.addActionListener(this);
    }//GEN-LAST:event_ensaladaActionPerformed

    private void pureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pureActionPerformed
        // TODO add your handling code here:
        numProducto = 2;
         this.pure.addActionListener(this);
    }//GEN-LAST:event_pureActionPerformed

    private void gaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaseosaActionPerformed
        // TODO add your handling code here:
        
        numProducto = 8;
        this.gaseosa.addActionListener(this);
    }//GEN-LAST:event_gaseosaActionPerformed

    private void cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeActionPerformed
        // TODO add your handling code here:
       
        numProducto = 9;
        this.cafe.addActionListener(this);
    }//GEN-LAST:event_cafeActionPerformed

    private void teActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teActionPerformed
        // TODO add your handling code here:
       
        numProducto = 10;
        this.te.addActionListener(this);
    }//GEN-LAST:event_teActionPerformed

    private void naturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naturalActionPerformed
        // TODO add your handling code here:
        
        numProducto = 11;
         this.natural.addActionListener(this);
         
    }//GEN-LAST:event_naturalActionPerformed

    private void frozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frozenActionPerformed
        // TODO add your handling code here:
       
        numProducto = 12;
        this.frozen.addActionListener(this);
    }//GEN-LAST:event_frozenActionPerformed

    private void batidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batidoActionPerformed
        // TODO add your handling code here:
        
        numProducto = 13;
        this.batido.addActionListener(this);
    }//GEN-LAST:event_batidoActionPerformed

    private void polloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polloActionPerformed
        // TODO add your handling code here:
        
         numPlatoFuerte = 2;
         this.pollo.addActionListener(this);
    }//GEN-LAST:event_polloActionPerformed

    private void sandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichActionPerformed
        // TODO add your handling code here:
        
         numPlatoFuerte = 5;
         this.sandwich.addActionListener(this);
    }//GEN-LAST:event_sandwichActionPerformed

    private void wrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrapActionPerformed
        // TODO add your handling code here:
     
         numPlatoFuerte = 6;
         this.wrap.addActionListener(this);
    }//GEN-LAST:event_wrapActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
        
         numPlatoFuerte = 4;
         this.pizza.addActionListener(this);
    }//GEN-LAST:event_pizzaActionPerformed

    private void hamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguesaActionPerformed
        // TODO add your handling code here:
       
         numPlatoFuerte = 1;
         this.hamburguesa.addActionListener(this);
          
    }//GEN-LAST:event_hamburguesaActionPerformed

    private void hotdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotdogActionPerformed
        // TODO add your handling code
         numPlatoFuerte = 3;
         this.hotdog.addActionListener(this);
    }//GEN-LAST:event_hotdogActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batido;
    private javax.swing.JButton cafe;
    private javax.swing.JButton combo1;
    private javax.swing.JButton combo2;
    private javax.swing.JButton combo3;
    private javax.swing.JButton combo4;
    private javax.swing.JButton combo5;
    private javax.swing.JButton combo6;
    private javax.swing.JButton ensalada;
    private javax.swing.JButton frozen;
    private javax.swing.JButton gaseosa;
    private javax.swing.JButton hamburguesa;
    private javax.swing.JButton hotdog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton maiz;
    private javax.swing.JButton natural;
    private javax.swing.JButton pagar;
    private javax.swing.JButton papas;
    private javax.swing.JButton patatas;
    private javax.swing.JButton pedir;
    private javax.swing.JButton pizza;
    private javax.swing.JButton pollo;
    private javax.swing.JButton pure;
    private javax.swing.JButton sandwich;
    private javax.swing.JButton te;
    private javax.swing.JButton tresleches;
    private javax.swing.JButton uvas;
    private javax.swing.JButton wrap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        
         if(ae.getSource().equals(combo1) || ae.getSource().equals(combo2) ||
            ae.getSource().equals(combo3) || ae.getSource().equals(combo4) ||
            ae.getSource().equals(combo5) || ae.getSource().equals(combo6)){
             Combo comboselect = buscarCombo(numCombo);
             hamburguesa.setEnabled(false);
             pizza.setEnabled(false);
             pollo.setEnabled(false);
             hotdog.setEnabled(false);
             sandwich.setEnabled(false);
             wrap.setEnabled(false);
             System.out.println("cancelamos los platos fuertes");
             pedidos.add(comboselect);
             pedido = comboselect;
              System.out.println("imprimiendo lista pedidos "+pedidos);
             combo1.setEnabled(false);
             combo2.setEnabled(false);
             combo3.setEnabled(false);
             combo4.setEnabled(false);
             combo5.setEnabled(false);
             combo6.setEnabled(false);
             
             System.out.println("holaaa mundooo combos");
         }
         else if(ae.getSource().equals(hamburguesa) || ae.getSource().equals(pollo) ||
                ae.getSource().equals(wrap) || ae.getSource().equals(sandwich) ||
                ae.getSource().equals(hotdog) || ae.getSource().equals(pizza) ){
                PlatoFuerte platof = buscarPlatoFuerte(numPlatoFuerte);
                combo1.setEnabled(false);
                combo2.setEnabled(false);
                combo3.setEnabled(false);
                combo4.setEnabled(false);
                combo5.setEnabled(false);
                combo6.setEnabled(false);
                System.out.println("cancelamos los combos   " + platofuerte);
                pedidos.add(platof);
                platofuerte =platof;
                System.out.println(""+pedidos);
                hamburguesa.setEnabled(false);
                pizza.setEnabled(false);
                pollo.setEnabled(false);
                hotdog.setEnabled(false);
                sandwich.setEnabled(false);
                wrap.setEnabled(false);
                System.out.println("holaaa mundooo fuertes");

        }
        else if(ae.getSource().equals(pedir)){
            if(pedido!=null){
             System.out.println("codigo combo"+pedido.getCodigo());  
             fac.crearPedido(pedido.getCodigo(), platofuerte, productos);
              System.out.println("pedido de combo + adicionales realizado" );
            }else{
                fac.crearPedido(0, platofuerte, productos);
                System.out.println("pedido de plato fuerte + adicionales realizado" );
            }
            hamburguesa.setEnabled(true); 
             pizza.setEnabled(true); 
             pollo.setEnabled(true); 
             hotdog.setEnabled(true); 
             sandwich.setEnabled(true); 
             wrap.setEnabled(true); 
             combo1.setEnabled(true); 
             combo2.setEnabled(true); 
             combo3.setEnabled(true); 
             combo4.setEnabled(true); 
             combo5.setEnabled(true); 
             combo6.setEnabled(true); 
            pedido = null;
            platofuerte=null;
            productos.clear();
        }
        else if(ae.getSource().equals(pagar)){
            //RECORRA PEDIDOS Y SUME TODo, imprima en el panel
            pagar(); 
            pedidos.clear();
            pedido = null;
            platofuerte=null;
            productos.clear();
        }else{
            Producto producto = buscarProducto(numProducto);
            productos.add(producto);
            pedidos.add(producto);
        }
          imprimir();
        
    }
   
    public Combo buscarCombo(int cod){
        for(Combo combo: Cliente.combos ){
            if(combo.getCodigo() == cod){
                return combo;
            }
            
        } 
        return null;
    }

    public PlatoFuerte buscarPlatoFuerte(int cod){
        for(PlatoFuerte plato: Cliente.platosfuertes ){
            if(plato.getCodigo() == cod){
                return plato;
            }
            
        } 
        return null;

    }
    public Producto buscarProducto(int cod){
       
        for(Producto producto: Cliente.products ){
            if(producto.getCodigo() == cod){
                return producto;
            }
            
        } 
        return null;
    }
    
    public void pagar(){
        int total=0;
        for(int i = 0; i < pedidos.size(); i++){
            if(pedidos.get(i) instanceof Combo){
                Combo auxC = (Combo) pedidos.get(i);
                jTextArea1.append("*****Combo " + auxC.getCodigo()+ "*****" + '\n');
                PlatoFuerte auxP = auxC.getPlatoFuerte();
                ArrayList<Adicional> auxa = auxC.getAdicionales();
                ArrayList<Bebida> auxb = auxC.getBebidas();
                jTextArea1.append("Plato Fuerte " + auxP.getNombre() + " precio " + auxP.getPrecio()+ '\n');
                total += auxP.getPrecio();
                for(int j = 0; j < auxa.size(); j++){
                    Adicional ad = auxa.get(j);
                    total += ad.getPrecio();
                    jTextArea1.append("Adicional " + ad.getNombre()+ " precio "+ad.getPrecio()+ '\n');
                }
                for(int k = 0; k < auxb.size(); k++){
                    Bebida beb = auxb.get(k);
                    total += beb.getPrecio();
                    jTextArea1.append("Bebida " + beb.getNombre()+ " precio "+beb.getPrecio()+ '\n');
                }   
            }
             if(pedidos.get(i) instanceof PlatoFuerte){
                  PlatoFuerte auxPf = (PlatoFuerte) pedidos.get(i);
                  total += auxPf.getPrecio();
                  jTextArea1.append("*****Plato Fuerte***** " + auxPf.getNombre() + " precio " + auxPf.getPrecio()+ '\n');
                
            }
              if(pedidos.get(i) instanceof Producto){
                   Producto auxpr = (Producto) pedidos.get(i);
                   total += auxpr.getPrecio();
                   jTextArea1.append("Producto adicional " + auxpr.getNombre() + " precio " + auxpr.getPrecio()+ '\n'); 
                
            }
        }
         jTextArea1.append("total " + total); 
    }
    public void imprimir(){
       
        System.out.println("Combo "+ pedido);
        System.out.println("plato fuerte "+ platofuerte);
        System.out.println("pedidos lista "+ pedidos);
        System.out.println("productos lista "+ productos);
        System.out.println("num combo "+ numCombo);
        System.out.println("num plato fuerte "+ numPlatoFuerte);
        System.out.println("num producto "+ numProducto);
     
   
    }
    /*public Producto buscarProducto(int cod){
        for(int i = 0; i < Cliente.inventario.size(); i++){
            if(Cliente.inventario.get(i) instanceof Producto){
                ArrayList<Producto> products = Producto Cliente.inventario.get(i);
                for(Producto producto: products ){
                    if(producto.getCodigo() == cod){
                        return producto;
                    }
                
                }
            }
                
        }
         return null;

    }*/
    
    /*if(seleccionCombo){ // si esta en true es que seleccionó combo, false es platofuerte
             Combo comboSeleccionado = buscarCombo(numCombo);
             hamburguesa.disable();
             pizza.disable();
             pollo.disable();
             hotdog.disable();
             sandwich.disable();
             wrap.disable();
             System.out.println("cancelamos los platos fuertes");
             pedido = comboSeleccionado;
             pedidos.add(pedido);
             combo1.disable();
             combo2.disable();
             combo3.disable();
             combo4.disable();
             combo5.disable();
             combo6.disable();


         }else if(!seleccionCombo){
             platofuerte = buscarPlatoFuerte(numPlatoFuerte);
             combo1.disable();
             combo2.disable();
             combo3.disable();
             combo4.disable();
             combo5.disable();
             combo6.disable();
             System.out.println("cancelamos los combos");
             pedido.setPlatoFuerte(platofuerte); 
             pedidos.add(platofuerte);
             hamburguesa.disable();
             pizza.disable();
             pollo.disable();
             hotdog.disable();
             sandwich.disable();
             wrap.disable();

         }*/
    
}
