/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caso1;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author raque
 */
public class mainUsuario extends javax.swing.JFrame implements ActionListener{

    
     private Combo pedido;
     private PlatoFuerte platofuerte;
     private ArrayList<Object> pedidos;
     private ArrayList<Producto> productos;
     private boolean seleccionCombo;
     private boolean combOPlatoF;
     private boolean selectBebidas;
     
   
//no me sirve que reciba una lista de productos porque debo recorrerla innecesariamente
    /**
     * Creates new form mainUsuario
     */
    public mainUsuario() {
        initComponents();
        pedidos = new ArrayList<>();
        productos = new ArrayList<>();
        seleccionCombo = false;
        combOPlatoF = false;
        selectBebidas = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo2 = new javax.swing.JButton();
        combo3 = new javax.swing.JButton();
        combo4 = new javax.swing.JButton();
        combo5 = new javax.swing.JButton();
        combo6 = new javax.swing.JButton();
        combo1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        uvas = new javax.swing.JButton();
        patatas = new javax.swing.JButton();
        maiz = new javax.swing.JButton();
        tresleches = new javax.swing.JButton();
        pure = new javax.swing.JButton();
        papas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ensalada = new javax.swing.JButton();
        cafe = new javax.swing.JButton();
        te = new javax.swing.JButton();
        natural = new javax.swing.JButton();
        frozen = new javax.swing.JButton();
        gaseosa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        batido = new javax.swing.JButton();
        pedir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pollo = new javax.swing.JButton();
        sandwich = new javax.swing.JButton();
        wrap = new javax.swing.JButton();
        pizza = new javax.swing.JButton();
        hamburguesa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hotdog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo2.setText("2");
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, 80));

        combo3.setText("3");
        combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3ActionPerformed(evt);
            }
        });
        getContentPane().add(combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, 80));

        combo4.setText("4");
        combo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4ActionPerformed(evt);
            }
        });
        getContentPane().add(combo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 100, 80));

        combo5.setText("5");
        combo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo5ActionPerformed(evt);
            }
        });
        getContentPane().add(combo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 100, 80));

        combo6.setText("6");
        combo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo6ActionPerformed(evt);
            }
        });
        getContentPane().add(combo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 100, 80));

        combo1.setText("1");
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, 80));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel1.setText("COMBOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 290, -1));

        uvas.setText("UVAS");
        uvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvasActionPerformed(evt);
            }
        });
        getContentPane().add(uvas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 80));

        patatas.setText("PATATAS");
        patatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patatasActionPerformed(evt);
            }
        });
        getContentPane().add(patatas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 100, 80));

        maiz.setText("MAÍZ");
        maiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maizActionPerformed(evt);
            }
        });
        getContentPane().add(maiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 100, 80));

        tresleches.setText("3 LECHES");
        tresleches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treslechesActionPerformed(evt);
            }
        });
        getContentPane().add(tresleches, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 100, 80));

        pure.setText("PURÉ");
        pure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pureActionPerformed(evt);
            }
        });
        getContentPane().add(pure, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 100, 80));

        papas.setText("PAPAS");
        papas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papasActionPerformed(evt);
            }
        });
        getContentPane().add(papas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 80));

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel2.setText("ADICIONALES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 270, 30));

        ensalada.setText("ENSALADA");
        ensalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensaladaActionPerformed(evt);
            }
        });
        getContentPane().add(ensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 100, 80));

        cafe.setText("CAFÉ");
        cafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cafeActionPerformed(evt);
            }
        });
        getContentPane().add(cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, 80));

        te.setText("TÉ");
        te.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teActionPerformed(evt);
            }
        });
        getContentPane().add(te, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 100, 80));

        natural.setText("NATURAL");
        natural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naturalActionPerformed(evt);
            }
        });
        getContentPane().add(natural, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 100, 80));

        frozen.setText("FROZEN");
        frozen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frozenActionPerformed(evt);
            }
        });
        getContentPane().add(frozen, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 460, 100, 80));

        gaseosa.setText("GASEOSA");
        gaseosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaseosaActionPerformed(evt);
            }
        });
        getContentPane().add(gaseosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 80));

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel3.setText("BEBIDAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 293, 82));

        pagar.setText("PAGAR");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });
        getContentPane().add(pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 110, 40));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 111, 375, 558));

        batido.setText("BATIDO");
        batido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batidoActionPerformed(evt);
            }
        });
        getContentPane().add(batido, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 100, 80));

        pedir.setText("PEDIR");
        pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirActionPerformed(evt);
            }
        });
        getContentPane().add(pedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 110, 40));

        jLabel4.setText("Sandwich, refresco, patatas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel5.setText("wrap,papas, refresco");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        jLabel6.setText("Hamburguesa, papas, refresco");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel7.setText("pizza, maíz, refresco");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel8.setText("pollo, puré, refresco");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jLabel9.setText("hot dog, ensalada, refresco");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 48)); // NOI18N
        jLabel10.setText("COMBOSTAR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 293, 82));

        pollo.setText("POLLO");
        pollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polloActionPerformed(evt);
            }
        });
        getContentPane().add(pollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 100, 80));

        sandwich.setText("SANDWICH");
        sandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwichActionPerformed(evt);
            }
        });
        getContentPane().add(sandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 100, 80));

        wrap.setText("WRAP");
        wrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrapActionPerformed(evt);
            }
        });
        getContentPane().add(wrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 100, 80));

        pizza.setText("PIZZA");
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });
        getContentPane().add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 100, 80));

        hamburguesa.setText("HAMBURGUESA");
        hamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguesaActionPerformed(evt);
            }
        });
        getContentPane().add(hamburguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 120, 80));

        jLabel11.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel11.setText("PLATOS FUERTES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 293, 82));

        hotdog.setText("HOT DOG");
        hotdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotdogActionPerformed(evt);
            }
        });
        getContentPane().add(hotdog, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 100, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        // TODO add your handling code here:
         this.pagar.addActionListener(this);  
    }//GEN-LAST:event_pagarActionPerformed

    private void pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirActionPerformed
        // TODO add your handling code here:
         this.pedir.addActionListener(this);
    }//GEN-LAST:event_pedirActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
        seleccionCombo = true;
        combOPlatoF = true;
        this.combo1.addActionListener(this);
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        // TODO add your handling code here:
        seleccionCombo = true;
        combOPlatoF = true;
        this.combo2.addActionListener(this);
        
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3ActionPerformed
        // TODO add your handling code here:
        seleccionCombo = true;
        combOPlatoF = true;
        this.combo3.addActionListener(this);
        
    }//GEN-LAST:event_combo3ActionPerformed

    private void combo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4ActionPerformed
        // TODO add your handling code here:
        seleccionCombo = true;
        combOPlatoF = true;
        this.combo4.addActionListener(this);
      
    }//GEN-LAST:event_combo4ActionPerformed

    private void combo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo5ActionPerformed
        // TODO add your handling code here:
        seleccionCombo = true;
        combOPlatoF = true;
        this.combo5.addActionListener(this);
      
        
    }//GEN-LAST:event_combo5ActionPerformed

    private void combo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo6ActionPerformed
        // TODO add your handling code here:
        seleccionCombo = true;
        combOPlatoF = true;
        this.combo6.addActionListener(this);
       
    }//GEN-LAST:event_combo6ActionPerformed

    private void papasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papasActionPerformed
        // TODO add your handling code here:
        this.papas.addActionListener(this);
    }//GEN-LAST:event_papasActionPerformed

    private void uvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvasActionPerformed
        // TODO add your handling code here:
        this.uvas.addActionListener(this);
    }//GEN-LAST:event_uvasActionPerformed

    private void patatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patatasActionPerformed
        // TODO add your handling code here:
         this.patatas.addActionListener(this);
    }//GEN-LAST:event_patatasActionPerformed

    private void maizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maizActionPerformed
        // TODO add your handling code here:
        this.maiz.addActionListener(this);
    }//GEN-LAST:event_maizActionPerformed

    private void treslechesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treslechesActionPerformed
        // TODO add your handling code here:
        this.tresleches.addActionListener(this);
    }//GEN-LAST:event_treslechesActionPerformed

    private void ensaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensaladaActionPerformed
        // TODO add your handling code here:
        this.ensalada.addActionListener(this);
    }//GEN-LAST:event_ensaladaActionPerformed

    private void pureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pureActionPerformed
        // TODO add your handling code here:
         this.pure.addActionListener(this);
    }//GEN-LAST:event_pureActionPerformed

    private void gaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaseosaActionPerformed
        // TODO add your handling code here:
        selectBebidas = true;
        this.pure.addActionListener(this);
    }//GEN-LAST:event_gaseosaActionPerformed

    private void cafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cafeActionPerformed
        // TODO add your handling code here:
        selectBebidas = true;
        this.cafe.addActionListener(this);
    }//GEN-LAST:event_cafeActionPerformed

    private void teActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teActionPerformed
        // TODO add your handling code here:
        selectBebidas = true;
        this.te.addActionListener(this);
    }//GEN-LAST:event_teActionPerformed

    private void naturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naturalActionPerformed
        // TODO add your handling code here:
        selectBebidas = true;
         this.natural.addActionListener(this);
         
    }//GEN-LAST:event_naturalActionPerformed

    private void frozenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frozenActionPerformed
        // TODO add your handling code here:
        selectBebidas = true;
        this.frozen.addActionListener(this);
    }//GEN-LAST:event_frozenActionPerformed

    private void batidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batidoActionPerformed
        // TODO add your handling code here:
        selectBebidas = true;
        this.batido.addActionListener(this);
    }//GEN-LAST:event_batidoActionPerformed

    private void polloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polloActionPerformed
        // TODO add your handling code here:
         combOPlatoF = true;
         this.pollo.addActionListener(this);
    }//GEN-LAST:event_polloActionPerformed

    private void sandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichActionPerformed
        // TODO add your handling code here:
        combOPlatoF = false;
         this.sandwich.addActionListener(this);
    }//GEN-LAST:event_sandwichActionPerformed

    private void wrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrapActionPerformed
        // TODO add your handling code here:
        combOPlatoF = false;
         this.wrap.addActionListener(this);
    }//GEN-LAST:event_wrapActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
        combOPlatoF = false;
         this.pizza.addActionListener(this);
    }//GEN-LAST:event_pizzaActionPerformed

    private void hamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguesaActionPerformed
        // TODO add your handling code here:
        combOPlatoF = false;
         this.hamburguesa.addActionListener(this);
          
    }//GEN-LAST:event_hamburguesaActionPerformed

    private void hotdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotdogActionPerformed
        // TODO add your handling code here:
        combOPlatoF = false;
         this.hotdog.addActionListener(this);
    }//GEN-LAST:event_hotdogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batido;
    private javax.swing.JButton cafe;
    private javax.swing.JButton combo1;
    private javax.swing.JButton combo2;
    private javax.swing.JButton combo3;
    private javax.swing.JButton combo4;
    private javax.swing.JButton combo5;
    private javax.swing.JButton combo6;
    private javax.swing.JButton ensalada;
    private javax.swing.JButton frozen;
    private javax.swing.JButton gaseosa;
    private javax.swing.JButton hamburguesa;
    private javax.swing.JButton hotdog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton maiz;
    private javax.swing.JButton natural;
    private javax.swing.JButton pagar;
    private javax.swing.JButton papas;
    private javax.swing.JButton patatas;
    private javax.swing.JButton pedir;
    private javax.swing.JButton pizza;
    private javax.swing.JButton pollo;
    private javax.swing.JButton pure;
    private javax.swing.JButton sandwich;
    private javax.swing.JButton te;
    private javax.swing.JButton tresleches;
    private javax.swing.JButton uvas;
    private javax.swing.JButton wrap;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(combOPlatoF){ //este amiguito valida que solo se inserte un combo o un plato fuerte en la lista pedido 
           if(seleccionCombo){
                Combo comboSeleccionado = buscarCombo(ae.getClass().getName());
                hamburguesa.disable();
                pizza.disable();
                pollo.disable();
                hotdog.disable();
                sandwich.disable();
                wrap.disable();
                System.out.println("cancelamos los platos fuertes");
                pedido = comboSeleccionado;
                pedidos.add(pedido);
                

            }else{
                PlatoFuerte platoFuerte = buscarPlatoFuerte(ae.getClass().getName());
                combo1.disable();
                combo2.disable();
                combo3.disable();
                combo4.disable();
                combo5.disable();
                combo6.disable();
                System.out.println("cancelamos los combos");
                pedido.setPlatoFuerte(platoFuerte); 
                pedidos.add(platofuerte);
            }
           
            combOPlatoF = false;   
        }
        else {
            JOptionPane.showMessageDialog(null,"Solo puede agregar un combo o un plato fuerte");
        }
        if(ae.getSource().equals(pedir)){
             Factory.crearPedido(pedido.getCodigo(), platofuerte, productos);
             
      
        }
        else if(ae.getSource().equals(pagar)){
            //RECORRA PEDIDOS Y SUME TODo, imprima en el panel
            pedidos.clear();
        }else{
            Producto producto = buscarProducto(ae.getClass().getName());
            productos.add(producto);
            pedidos.add(producto);
        }
        
       
        
             
    }
    
  
    public Combo buscarCombo(String nombre){
         return null;

    }
    public PlatoFuerte buscarPlatoFuerte(String nombre){
         return null;

    }
    public Producto buscarProducto(String nombre){
         return null;

    }
    
}
